// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: C:/Users/Miguel Arquejada/Desktop/projetos/java/AnalisadorLexico2/gerador.flex

package lexer;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\6\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\3\u0100\1\u0e00\205\u0100\1\u0600\1\u0100\1\u0f00\1\u1000\1\u1100"+
    "\1\u1200\54\u0100\10\u1300\37\u0100\1\u0900\4\u0100\1\u1400\10\u0100"+
    "\1\u1500\2\u0100\1\u1600\1\u1700\1\u1200\1\u0100\1\u0500\1\u0100"+
    "\1\u1800\1\u1500\1\u0800\3\u0100\1\u1100\1\u1900\114\u0100\1\u1a00"+
    "\1\u1100\153\u0100\1\u1b00\11\u0100\1\u1c00\1\u1200\6\u0100\1\u1100"+
    "\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\2\0\1\10\1\11\1\0\2\12\1\13\1\14"+
    "\1\12\1\15\1\16\1\17\12\20\1\0\1\12\1\6"+
    "\1\21\1\6\2\0\4\22\1\23\15\22\1\24\7\22"+
    "\1\12\1\0\1\12\1\0\1\22\1\0\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\2\22"+
    "\1\36\1\37\1\40\1\41\1\42\1\22\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\22\1\51\1\22\1\12"+
    "\1\52\1\12\7\0\1\3\u01da\0\12\20\206\0\12\20"+
    "\306\0\12\20\234\0\12\20\166\0\12\20\140\0\12\20"+
    "\166\0\12\20\106\0\12\20\u0116\0\12\20\106\0\12\20"+
    "\u0146\0\12\20\46\0\12\20\u012c\0\12\20\200\0\12\20"+
    "\246\0\12\20\6\0\12\20\266\0\12\20\126\0\12\20"+
    "\206\0\12\20\6\0\12\20\316\0\2\3\u01a6\0\12\20"+
    "\46\0\12\20\306\0\12\20\26\0\12\20\126\0\12\20"+
    "\u0196\0\12\20\6\0\u0100\3\240\0\12\20\206\0\12\20"+
    "\u012c\0\12\20\200\0\12\20\74\0\12\20\220\0\12\20"+
    "\166\0\12\20\146\0\12\20\206\0\12\20\106\0\12\20"+
    "\266\0\12\20\u0164\0\62\20\100\0\12\20\266\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[7424];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\1\1\3\1\1"+
    "\1\4\2\3\1\1\1\3\1\5\20\6\1\1\1\0"+
    "\1\7\1\0\1\5\1\0\1\2\2\10\12\6\1\11"+
    "\13\6\2\0\1\5\10\6\1\11\14\6\1\11\7\6"+
    "\1\0\3\6\1\0\2\6\1\11\2\6";

  private static int [] zzUnpackAction() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\53\0\126\0\201\0\254\0\53\0\327"+
    "\0\53\0\u0102\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204"+
    "\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c"+
    "\0\u0387\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489\0\254"+
    "\0\254\0\u0158\0\u04b4\0\u04df\0\u050a\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3"+
    "\0\u070e\0\u01d9\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810"+
    "\0\u083b\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968"+
    "\0\u0993\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0"+
    "\0\u0aeb\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\u0bed\0\u0c18"+
    "\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a\0\u0d45\0\u0d70"+
    "\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8"+
    "\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74\0\53\0\u0f9f\0\u0fca";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\2\1\4\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\7\1\12\1\13\1\14\1\15\1\16"+
    "\1\5\2\17\1\20\1\17\1\21\1\22\1\23\1\24"+
    "\1\25\2\17\1\26\1\27\1\30\2\17\1\31\1\32"+
    "\1\33\1\34\1\17\1\35\1\36\1\17\1\37\55\0"+
    "\1\3\71\0\1\7\31\0\2\40\3\0\2\40\1\41"+
    "\43\40\11\0\1\7\55\0\1\7\1\0\1\42\1\0"+
    "\1\16\1\7\46\0\1\7\1\42\1\0\1\16\1\7"+
    "\51\0\1\43\45\0\1\44\3\0\1\45\51\0\1\42"+
    "\1\0\1\16\1\0\1\46\1\47\5\46\1\47\20\46"+
    "\21\0\1\17\1\0\30\17\21\0\1\17\1\0\23\17"+
    "\1\50\4\17\21\0\1\17\1\0\17\17\1\51\7\17"+
    "\1\52\21\0\1\17\1\0\12\17\1\53\1\17\1\54"+
    "\13\17\21\0\1\17\1\0\17\17\1\55\10\17\21\0"+
    "\1\17\1\0\14\17\1\56\13\17\21\0\1\17\1\0"+
    "\3\17\1\57\10\17\1\60\2\17\1\61\10\17\21\0"+
    "\1\17\1\0\10\17\1\62\5\17\1\63\11\17\21\0"+
    "\1\17\1\0\17\17\1\64\10\17\21\0\1\17\1\0"+
    "\3\17\1\65\24\17\21\0\1\17\1\0\21\17\1\66"+
    "\2\17\1\67\3\17\21\0\1\17\1\0\7\17\1\70"+
    "\20\17\21\0\1\17\1\0\12\17\1\71\10\17\1\72"+
    "\4\17\21\0\1\17\1\0\21\17\1\73\6\17\21\0"+
    "\1\17\1\0\17\17\1\74\10\17\21\0\1\17\1\0"+
    "\12\17\1\75\15\17\53\0\1\7\20\0\1\43\1\0"+
    "\1\46\1\47\5\46\1\47\20\46\1\0\13\44\1\76"+
    "\37\44\2\45\1\0\1\45\1\0\46\45\22\0\30\46"+
    "\15\0\2\77\2\0\1\100\1\0\30\46\21\0\1\17"+
    "\1\0\21\17\1\101\6\17\21\0\1\17\1\0\17\17"+
    "\1\102\10\17\21\0\1\17\1\0\23\17\1\103\4\17"+
    "\21\0\1\17\1\0\3\17\1\61\24\17\21\0\1\17"+
    "\1\0\3\17\1\104\24\17\21\0\1\17\1\0\24\17"+
    "\1\105\3\17\21\0\1\17\1\0\22\17\1\106\5\17"+
    "\21\0\1\17\1\0\14\17\1\107\13\17\21\0\1\17"+
    "\1\0\17\17\1\110\10\17\21\0\1\17\1\0\21\17"+
    "\1\62\6\17\21\0\1\17\1\0\23\17\1\111\4\17"+
    "\21\0\1\17\1\0\16\17\1\112\11\17\21\0\1\17"+
    "\1\0\13\17\1\113\14\17\21\0\1\17\1\0\13\17"+
    "\1\114\3\17\1\115\10\17\21\0\1\17\1\0\4\17"+
    "\1\116\23\17\21\0\1\17\1\0\23\17\1\117\4\17"+
    "\21\0\1\17\1\0\17\17\1\120\10\17\21\0\1\17"+
    "\1\0\3\17\1\121\15\17\1\101\6\17\21\0\1\17"+
    "\1\0\24\17\1\103\3\17\21\0\1\17\1\0\13\17"+
    "\1\122\14\17\21\0\1\17\1\0\13\17\1\123\14\17"+
    "\20\0\1\3\53\0\1\100\52\0\1\100\1\0\30\46"+
    "\21\0\1\17\1\0\13\17\1\64\14\17\21\0\1\17"+
    "\1\0\14\17\1\124\13\17\21\0\1\17\1\0\7\17"+
    "\1\62\20\17\21\0\1\17\1\0\22\17\1\125\5\17"+
    "\21\0\1\17\1\0\4\17\1\123\23\17\21\0\1\17"+
    "\1\0\7\17\1\126\20\17\21\0\1\17\1\0\22\17"+
    "\1\103\5\17\21\0\1\17\1\0\3\17\1\127\24\17"+
    "\21\0\1\17\1\0\7\17\1\130\20\17\21\0\1\17"+
    "\1\0\11\17\1\62\16\17\21\0\1\17\1\0\16\17"+
    "\1\62\11\17\21\0\1\17\1\0\25\17\1\131\2\17"+
    "\21\0\1\17\1\0\23\17\1\132\4\17\21\0\1\17"+
    "\1\0\14\17\1\133\13\17\21\0\1\17\1\0\24\17"+
    "\1\134\3\17\21\0\1\17\1\0\21\17\1\127\6\17"+
    "\21\0\1\17\1\0\23\17\1\133\4\17\21\0\1\17"+
    "\1\0\6\17\1\62\21\17\21\0\1\17\1\0\14\17"+
    "\1\103\13\17\21\0\1\17\1\0\7\17\1\135\20\17"+
    "\21\0\1\17\1\0\22\17\1\62\5\17\6\0\1\136"+
    "\12\0\1\17\1\0\30\17\21\0\1\17\1\0\23\17"+
    "\1\62\4\17\21\0\1\17\1\0\21\17\1\137\6\17"+
    "\21\0\1\17\1\0\3\17\1\52\24\17\21\0\1\17"+
    "\1\0\7\17\1\140\20\17\21\0\1\17\1\0\13\17"+
    "\1\141\14\17\21\0\1\17\1\0\21\17\1\113\6\17"+
    "\21\0\1\17\1\0\3\17\1\113\24\17\36\0\1\142"+
    "\35\0\1\17\1\0\10\17\1\143\17\17\21\0\1\17"+
    "\1\0\5\17\1\144\22\17\21\0\1\17\1\0\5\17"+
    "\1\62\22\17\33\0\1\145\40\0\1\17\1\0\3\17"+
    "\1\146\24\17\21\0\1\17\1\0\23\17\1\147\4\17"+
    "\21\0\1\17\1\0\5\17\1\103\22\17\21\0\1\17"+
    "\1\0\7\17\1\122\20\17\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4085];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\1\1\1\11\26\1\1\0"+
    "\1\1\1\0\1\1\1\0\31\1\2\0\36\1\1\0"+
    "\3\1\1\0\2\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[103];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("IllegalExpression \"" + yytext() + "\" na linha " + yyline + " e coluna " + yycolumn);
            }
            // fall through
          case 10: break;
          case 2:
            { /*não fazer nada*/
            }
            // fall through
          case 11: break;
          case 3:
            { return new Token(yytext(),Type.OPERADOR);
            }
            // fall through
          case 12: break;
          case 4:
            { return new Token(yytext(),Type.SIMBOLO);
            }
            // fall through
          case 13: break;
          case 5:
            { return new Token(yytext(),Type.CONSTANTE);
            }
            // fall through
          case 14: break;
          case 6:
            { return new Token(yytext(),Type.IDENTIFICADOR);
            }
            // fall through
          case 15: break;
          case 7:
            { return new Token(yytext(),Type.STRING);
            }
            // fall through
          case 16: break;
          case 8:
            { throw new Error("Identificador invalido: \"" + yytext() + "\" na linha " + yyline + " e coluna " + yycolumn);
            }
            // fall through
          case 17: break;
          case 9:
            { return new Token(yytext(),Type.PALAVRA_RESERVADA);
            }
            // fall through
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
